In [1]:
import numpy as np


In [2]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [3]:
x=np.array([[1,2,3],[2,3,4]])

In [5]:
np.greater(9,8)

True

In [6]:
np.greater_equal(10,10)

True

In [7]:
x=9
y=8
np.less_equal(x,y)

False

In [8]:
np.less(8,9)

True

In [10]:
np.array([[1,0,0],[0,1,0],[0,0,1]])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [108]:
x = np.array([1,2,3])

y = np.array([7,8,9])
print(np.greater( x,y))
print(np.greater_equal( x,y))
print(np.less_equal( x,y))
print(np.less( x,y))

[False False False]
[False False False]
[ True  True  True]
[ True  True  True]


In [109]:
y=np.arange(30,71,2)
print(y)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [110]:
m = np.identity(3, dtype=int)
print(m)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [13]:
x[(x>=9) & (x<=15)]*=-1
print(x)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [14]:
y=np.zeros((5, 5),dtype=int)
print(y)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [16]:
np.fill_diagonal(y,[1,2,3,4,5])
print(y)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [25]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.sum(z)

45

In [26]:
np.sum(z,axis=0)

array([12, 15, 18])

In [28]:
np.sum(z,axis=1)

array([ 6, 15, 24])

In [82]:
np.savetxt("new.txt",z)
f=np.loadtxt("new.txt")
print(f)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [122]:
z2=np.array([[1,2,3],[4,5,6],[7,8,9]])
# np.all(z==z2)
z3=np.array_equal(z,z2)
if z3:
    print("Equal")
else:
    print("Not equal!")

Equal


In [41]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
m = np.arange(1,5)
np.resize(m,(1,2))

array([[1, 2]])

In [115]:
a=np.array([[1,2,3],[4,5,6],[1,4,5]])
print(a)
a1=a
a1[[0,2],:]=a1[[2,0],:]

print(a1)

[[1 2 3]
 [4 5 6]
 [1 4 5]]
[[1 4 5]
 [4 5 6]
 [1 2 3]]


In [119]:
# print(a*a1)
print(a1)
print(a)
np.multiply(a,a1)

[[1 4 5]
 [4 5 6]
 [1 2 3]]
[[1 4 5]
 [4 5 6]
 [1 2 3]]


array([[ 1, 16, 25],
       [16, 25, 36],
       [ 1,  4,  9]])