In [1]:
import numpy as np
a=[[],[]]
b=[[],[]]
print("Elements of first array")
for i in range(2):
    for j in range(2):
        a[i].append(int(input()))
print("Elements of second array")
for i in range(2):
    for j in range(2):
        b[i].append(int(input()))
a=np.array(a)
b=np.array(b)
print(a)
print(b)

Elements of first array
1
2
3
4
Elements of second array
2
3
4
5
[[1 2]
 [3 4]]
[[2 3]
 [4 5]]


In [2]:
a.dot(b)
# a@b

array([[10, 13],
       [22, 29]])

In [4]:
# a.T
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [6]:
np.linalg.matrix_rank(a)

2

In [7]:
np.trace(a)

5

In [8]:
np.linalg.det(a)

-2.0000000000000004

In [16]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [18]:
dir(np.linalg)

['LinAlgError',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_umath_linalg',
 'absolute_import',
 'cholesky',
 'cond',
 'det',
 'division',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'inv',
 'lapack_lite',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'print_function',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

In [19]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [21]:
np.linalg.eigvals(a)

array([-0.37228132,  5.37228132])